package by.zloy.interview

assert BalancedBrackets.isBalancedRecursion("()[]{}") == true : "Simple balanced brackets"
assert BalancedBrackets.isBalancedRecursion("([])") == true : "Nested balanced brackets"
assert BalancedBrackets.isBalancedRecursion("([)]") == false : "Mismatched nesting"
assert BalancedBrackets.isBalancedRecursion("") == true : "Empty string"
assert BalancedBrackets.isBalancedRecursion("()") == true : "Single pair parentheses"
assert BalancedBrackets.isBalancedRecursion("[]") == true : "Single pair square brackets"
assert BalancedBrackets.isBalancedRecursion("{}") == true : "Single pair curly braces"
assert BalancedBrackets.isBalancedRecursion("<>") == true : "Single pair angle brackets"
assert BalancedBrackets.isBalancedRecursion("((()))") == true : "Multiple nested parentheses"
assert BalancedBrackets.isBalancedRecursion("([{}])") == true : "All bracket types nested"
assert BalancedBrackets.isBalancedRecursion("([<{}>])") == true : "Deeply nested all types"
assert BalancedBrackets.isBalancedRecursion("(") == false : "Single open parenthesis"
assert BalancedBrackets.isBalancedRecursion(")") == false : "Single close parenthesis"
assert BalancedBrackets.isBalancedRecursion("(()") == false : "Unclosed parenthesis"
assert BalancedBrackets.isBalancedRecursion("())") == false : "Extra close parenthesis"
assert BalancedBrackets.isBalancedRecursion("([)]") == false : "Interleaved brackets"
assert BalancedBrackets.isBalancedRecursion("{{[[(())]]}}") == true : "Complex balanced"
assert BalancedBrackets.isBalancedRecursion("aa(bb[cc)dd]") == false : "Text with unbalanced brackets"
assert BalancedBrackets.isBalancedRecursion("a{}a[bb(cc)dd]") == true : "Text with balanced brackets"
assert BalancedBrackets.isBalancedRecursion("hello world") == true : "String without brackets"
assert BalancedBrackets.isBalancedRecursion("{{{}}}") == true : "Multiple same-type nested"
assert BalancedBrackets.isBalancedRecursion("}{") == false : "Reversed brackets"
assert BalancedBrackets.isBalancedRecursion("([{}<>])") == true : "All four types balanced"
assert BalancedBrackets.isBalancedRecursion("(([[{{<<>>}}]]))") == true : "Symmetric all types"
assert BalancedBrackets.isBalancedRecursion("(]") == false : "Mixed bracket pair"

assert BalancedBrackets.isBalanced("()[]{}") == true : "Simple balanced brackets"
assert BalancedBrackets.isBalanced("([])") == true : "Nested balanced brackets"
assert BalancedBrackets.isBalanced("([)]") == false : "Mismatched nesting"
assert BalancedBrackets.isBalanced("") == true : "Empty string"
assert BalancedBrackets.isBalanced("()") == true : "Single pair parentheses"
assert BalancedBrackets.isBalanced("[]") == true : "Single pair square brackets"
assert BalancedBrackets.isBalanced("{}") == true : "Single pair curly braces"
assert BalancedBrackets.isBalanced("<>") == true : "Single pair angle brackets"
assert BalancedBrackets.isBalanced("((()))") == true : "Multiple nested parentheses"
assert BalancedBrackets.isBalanced("([{}])") == true : "All bracket types nested"
assert BalancedBrackets.isBalanced("([<{}>])") == true : "Deeply nested all types"
assert BalancedBrackets.isBalanced("(") == false : "Single open parenthesis"
assert BalancedBrackets.isBalanced(")") == false : "Single close parenthesis"
assert BalancedBrackets.isBalanced("(()") == false : "Unclosed parenthesis"
assert BalancedBrackets.isBalanced("())") == false : "Extra close parenthesis"
assert BalancedBrackets.isBalanced("([)]") == false : "Interleaved brackets"
assert BalancedBrackets.isBalanced("{{[[(())]]}}") == true : "Complex balanced"
assert BalancedBrackets.isBalanced("aa(bb[cc)dd]") == false : "Text with unbalanced brackets"
assert BalancedBrackets.isBalanced("a{}a[bb(cc)dd]") == true : "Text with balanced brackets"
assert BalancedBrackets.isBalanced("hello world") == true : "String without brackets"
assert BalancedBrackets.isBalanced("{{{}}}") == true : "Multiple same-type nested"
assert BalancedBrackets.isBalanced("}{") == false : "Reversed brackets"
assert BalancedBrackets.isBalanced("([{}<>])") == true : "All four types balanced"
assert BalancedBrackets.isBalanced("(([[{{<<>>}}]]))") == true : "Symmetric all types"
assert BalancedBrackets.isBalanced("(]") == false : "Mixed bracket pair"

assert BalancedBrackets.isBalancedWithHashMap("()[]{}") == true : "Simple balanced brackets"
assert BalancedBrackets.isBalancedWithHashMap("([])") == true : "Nested balanced brackets"
assert BalancedBrackets.isBalancedWithHashMap("([)]") == false : "Mismatched nesting"
assert BalancedBrackets.isBalancedWithHashMap("") == true : "Empty string"
assert BalancedBrackets.isBalancedWithHashMap("()") == true : "Single pair parentheses"
assert BalancedBrackets.isBalancedWithHashMap("[]") == true : "Single pair square brackets"
assert BalancedBrackets.isBalancedWithHashMap("{}") == true : "Single pair curly braces"
assert BalancedBrackets.isBalancedWithHashMap("<>") == true : "Single pair angle brackets"
assert BalancedBrackets.isBalancedWithHashMap("((()))") == true : "Multiple nested parentheses"
assert BalancedBrackets.isBalancedWithHashMap("([{}])") == true : "All bracket types nested"
assert BalancedBrackets.isBalancedWithHashMap("([<{}>])") == true : "Deeply nested all types"
assert BalancedBrackets.isBalancedWithHashMap("(") == false : "Single open parenthesis"
assert BalancedBrackets.isBalancedWithHashMap(")") == false : "Single close parenthesis"
assert BalancedBrackets.isBalancedWithHashMap("(()") == false : "Unclosed parenthesis"
assert BalancedBrackets.isBalancedWithHashMap("())") == false : "Extra close parenthesis"
assert BalancedBrackets.isBalancedWithHashMap("([)]") == false : "Interleaved brackets"
assert BalancedBrackets.isBalancedWithHashMap("{{[[(())]]}}") == true : "Complex balanced"
assert BalancedBrackets.isBalancedWithHashMap("aa(bb[cc)dd]") == false : "Text with unbalanced brackets"
assert BalancedBrackets.isBalancedWithHashMap("a{}a[bb(cc)dd]") == true : "Text with balanced brackets"
assert BalancedBrackets.isBalancedWithHashMap("hello world") == true : "String without brackets"
assert BalancedBrackets.isBalancedWithHashMap("{{{}}}") == true : "Multiple same-type nested"
assert BalancedBrackets.isBalancedWithHashMap("}{") == false : "Reversed brackets"
assert BalancedBrackets.isBalancedWithHashMap("([{}<>])") == true : "All four types balanced"
assert BalancedBrackets.isBalancedWithHashMap("(([[{{<<>>}}]]))") == true : "Symmetric all types"
assert BalancedBrackets.isBalancedWithHashMap("(]") == false : "Mixed bracket pair"

println "All tests passed!"
